"""Add advisor and PM data

Revision ID: 0a8c859ce2f8
Revises: c4d906101275
Create Date: 2026-04-17 09:56:49.748339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8c859ce2f8'
down_revision: Union[str, Sequence[str], None] = 'c4d906101275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('advisor', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('advisor_email', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('advisor_phone', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('project_manager', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_manager')
    op.drop_column('projects', 'advisor_phone')
    op.drop_column('projects', 'advisor_email')
    op.drop_column('projects', 'advisor')
    # ### end Alembic commands ###
